### ISSUE TITLE
Social Media Hack

### ISSUE THREAD

**Issue by Crysis1120** [rixon-cochi/SMF#59]
Ist es möglich, dass Sie mir Zugang zu einem Instagram-, Facebook- oder Snapchat-Konto verschaffen? Benutzername + E-Mail ist vorhanden, aber leider kein Passwort mehr.
ich bitte um Hilfe ! Ich zahle gerne über Paypal.

**Comment by somethingcasual** [comment]
Hi, I noticed you closed this issue. I just wanna know did the hack work? Thanks!
